version: '3.8'

services:
  app:
    image: ${DOCKER_IMAGE_NAME:-dockerrep.registrucentras.lt:5000/self-service-jar-provider-ui}:${DOCKER_TAG:-latest}
    container_name: self-service-ui
    ports:
      - '${APP_PORT:-8080}:82'
    restart: unless-stopped
    environment:
      - NODE_ENV=production
    networks:
      - app-network
    healthcheck:
      test: ['CMD', 'wget', '--quiet', '--tries=1', '--spider', 'http://localhost:82']
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 40s
    logging:
      driver: 'json-file'
      options:
        max-size: '10m'
        max-file: '3'

networks:
  app-network:
    driver: bridge
